INSERT INTO runner (pnr, username, userpw, firstname, lastname, userinfo, runnerid, points, city, picture) VALUES ('9010242142', 'victor', 'pw', 'Victor', 'Karlsson', 'hejhej det är jag som är Victor', '23124', '0', 'Göteborg', '');
INSERT INTO runner (pnr, username, userpw, firstname, lastname, userinfo, runnerid, points, city, picture) VALUES ('8910152142', 'wiltord', 'pw', 'Viktor', 'Swantesson', 'hejhej det är jag som är Viktor', '23125', '0', 'Göteborg', '');
INSERT INTO runner (pnr, username, userpw, firstname, lastname, userinfo, runnerid, points, city, picture) VALUES ('8911232415', 'friskydingo', 'pw', 'David', 'Eriksson', 'hejhej det är jag som är David', '23126', '0', 'Göteborg', '');
INSERT INTO runner (pnr, username, userpw, firstname, lastname, userinfo, runnerid, points, city, picture) VALUES ('9003152142', 'daniel', 'pw', 'Daniel', 'Gunnarsson', 'hejhej det är jag som är Daniel', '23127', '0', 'Göteborg', '');
INSERT INTO runner (pnr, username, userpw, firstname, lastname, userinfo, runnerid, points, city, picture) VALUES ('8912112242', 'ohls', 'pw', 'Martin', 'Ohls', 'hejhej det är jag som är Martin', '23128', '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8448172560,"Moses","YAD75HTZ8ZD","Moses","Dominguez","In",1, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8767076938,"Hope","INN06MCL3YK","Hope","Eaton","ut nisi a odio",2, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (287386678,"Nehru","IRA04JRR5OZ","Nehru","Swanson","Pellentesque",3, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (5329252470,"Katell","HDR15OBU3CC","Katell","Benson","Sed",4, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (965505187,"Abdul","EKD89HAV3OC","Abdul","Casey","Mauris non dui nec urna",5, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8892183016,"Jasper","FNA60VVC1XG","Jasper","Obrien","Phasellus dapibus quam quis diam. Pellentesque",6, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4259630413,"Orla","EXS16AYU4WA","Orla","Todd","lectus pede et risus. Quisque libero lacus, varius et, euismod",7, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (3042101658,"Karyn","MMK98NIN1TR","Karyn","Walter","Duis",8, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (5552689144,"Dara","XOG92UZE2HR","Dara","Hill","Nunc ullamcorper, velit in aliquet lobortis, nisi nibh",9, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7311584786,"Troy","NFP26KUQ0JO","Troy","Miller","non massa non ante bibendum ullamcorper. Duis",10, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7641761246,"Nevada","JLL96LZC1SP","Nevada","Reilly","Aliquam ornare, libero at",11, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (2910031320,"Amber","KPT30FKQ9EZ","Amber","Davenport","Proin non massa non ante",12, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8145819887,"Trevor","QVR75ILH3TR","Trevor","Peck","risus. Donec nibh enim, gravida sit amet, dapibus id, blandit",13, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (5189826639,"Cadman","DEK22GML7HB","Cadman","Mcguire","Sed et libero. Proin mi. Aliquam gravida",14, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1123777130,"Camilla","NMC42MZY0MC","Camilla","Walsh","euismod et, commodo",15, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9103924884,"Shana","OBR73XEY8HL","Shana","Stokes","diam lorem, auctor quis,",16, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (5862766151,"Tanya","CFY53TJH8HW","Tanya","Rodgers","leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod",17, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (6458015497,"Dieter","DKN72JGC6VF","Dieter","Gardner","Nulla semper tellus id nunc interdum feugiat. Sed nec metus",18, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4612616243,"Howard","FJB42VRA8IE","Howard","Tyler","augue, eu tempor",19, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7675871930,"Anastasia","VUM12OSP9EV","Anastasia","Sykes","egestas rhoncus. Proin",20, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7607132521,"Zelenia","DCR53WEF8YB","Zelenia","Vaughn","pellentesque a, facilisis non, bibendum sed, est.",21, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (3153501347,"Clayton","FIP73OIG8CJ","Clayton","Koch","adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem",22, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4867180503,"Alexa","DMR04OOK6WP","Alexa","Schneider","sodales purus, in molestie tortor nibh sit amet orci. Ut",23, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9454118782,"Belle","SPX92BJT1WX","Belle","Porter","nibh vulputate mauris sagittis placerat. Cras dictum",24, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1135679594,"Kendall","RWM08EPS9NL","Kendall","Mitchell","eu augue porttitor interdum. Sed auctor",25, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4754820676,"Beau","GDL32YVZ3YR","Beau","Mercer","bibendum. Donec felis",26, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (2367189797,"Kaden","FGP07JPJ9CQ","Kaden","Sanford","mus. Proin",27, '0', 'Stockholm', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (133478153,"Mason","AFR18YXL7ER","Mason","Browning","Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis",28, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (6547878894,"Cullen","GXQ63LYF1ZF","Cullen","Faulkner","natoque penatibus et magnis dis",29, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (3627713605,"Alexander","FEB83JYK7PQ","Alexander","Simmons","nec urna suscipit nonummy. Fusce fermentum fermentum",30, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4440180598,"Yolanda","GVU43AFR4OW","Yolanda","Perry","convallis erat, eget tincidunt dui augue eu",31, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9823496926,"Tamara","JNG41LQA6CH","Tamara","Gates","egestas blandit. Nam nulla magna,",32, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (3539278155,"Tad","YED81WFW1FF","Tad","Kinney","luctus sit amet, faucibus ut, nulla. Cras",33, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1858599029,"Philip","XFZ70YFL4OJ","Philip","Pate","eu neque pellentesque massa lobortis ultrices. Vivamus",34, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8425580162,"Gavin","KDM20TEN0JL","Gavin","Quinn","consectetuer rhoncus. Nullam",35, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1997341984,"Shafira","JQL11XTW5PH","Shafira","Velasquez","ipsum non arcu. Vivamus sit amet risus. Donec",36, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (6708341442,"Adrienne","FMV67FLM1QW","Adrienne","Mckenzie","In nec orci. Donec nibh. Quisque nonummy ipsum",37, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (700656308,"Aiko","IMQ03JHG5YL","Aiko","Carroll","vitae risus. Duis a mi fringilla mi lacinia mattis. Integer",38, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (586432382,"Zephania","XGB82VQV2SE","Zephania","Craft","et magnis dis parturient montes, nascetur ridiculus",39, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (6891800557,"Althea","EGT82HCK4DH","Althea","Dominguez","ut, molestie in, tempus eu, ligula. Aenean",40, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8743358548,"Tana","YUC94OES9WW","Tana","Franklin","tellus. Phasellus elit",41, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1581944009,"Audrey","YFH82BOM5LK","Audrey","Berger","mus. Proin vel nisl.",42, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (3964981727,"Britanni","HZE78APF0UD","Britanni","Morse","et netus et",43, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (3797103827,"Isaac","ZNS75GHR6SY","Isaac","Vargas","in, cursus et, eros. Proin ultrices.",44, '0', 'Malmö', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8238437317,"Wendy","EDV62JPX3ZX","Wendy","Lucas","est arcu ac orci. Ut semper pretium neque. Morbi",45, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1004005938,"Grace","DNU64DII2DM","Grace","Osborne","fermentum vel, mauris. Integer",46, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4321546739,"Delilah","PKC03BFX7IB","Delilah","House","consequat dolor vitae",47, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4994296187,"Lisandra","UCQ44JZC0KR","Lisandra","Fowler","sociis natoque penatibus et magnis",48, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7874715997,"Barclay","OKM26LGC5TW","Barclay","Rodriguez","tristique ac, eleifend vitae, erat. Vivamus nisi.",49, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8320106231,"Charde","VFD99LCT1ZA","Charde","Bailey","magna. Ut tincidunt orci",51, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9567067751,"Aladdin","HRW12ZCK8YG","Aladdin","Page","Sed",52, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7575884680,"Hiroko","CVW29UOA3NH","Hiroko","Craft","scelerisque",53, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9768047473,"Kelly","HQD31JBW6VY","Kelly","Sutton","massa lobortis ultrices. Vivamus rhoncus.",54, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7166124678,"Lani","ZSE20TBH2AO","Lani","Carroll","gravida. Praesent eu nulla at sem molestie sodales. Mauris",55, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8251721554,"Thomas","OLB99VKV1DU","Thomas","Faulkner","amet massa. Quisque porttitor eros nec tellus. Nunc lectus",56, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7140196095,"Quincy","DIO18MBA2XP","Quincy","Sweeney","justo nec ante. Maecenas mi felis, adipiscing",57, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (2650724177,"Rogan","SKJ64MUS6NW","Rogan","Sawyer","arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.",58, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4083492907,"Patricia","NXZ16YQO0XH","Patricia","Hammond","lorem, luctus ut, pellentesque eget,",59, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4503759592,"Germaine","IGM18OZR5KE","Germaine","Gordon","erat volutpat. Nulla dignissim. Maecenas",60, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9387041220,"Rana","UCV68NGF7SO","Rana","Fry","Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie",61, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (6429605379,"Skyler","UMZ88YOE7NY","Skyler","Marsh","lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus.",62, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4574287171,"Drew","NVE35WVX9LR","Drew","Carey","in consequat enim diam vel",63, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4233534078,"William","AZB78YQK5CY","William","Carlson","taciti sociosqu ad litora",64, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (5310431292,"Shannon","QZC93FKM8VM","Shannon","Henderson","pede et risus. Quisque libero lacus, varius et, euismod",65, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9735900227,"Caldwell","UEG73IPM8DC","Caldwell","Ford","nec, mollis vitae, posuere at, velit. Cras lorem lorem,",66, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1330179376,"Ignacia","DEI70EVL0UF","Ignacia","Dennis","mauris, aliquam eu,",67, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1678869589,"Camden","BZF24RWT9AW","Camden","Mcleod","dui, semper",68, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8117678880,"James","WHU46JNX0SZ","James","Macdonald","dapibus",69, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (867911770,"Fulton","SKS89DMO3HK","Fulton","Levine","a neque. Nullam ut nisi a odio",70, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (2638795718,"Wing","PBM16OIF6LX","Wing","Odonnell","Donec",71, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9113239631,"Gillian","JPU70GBO3HE","Gillian","Wall","odio. Etiam ligula tortor, dictum",72, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1337208094,"Colt","ZEX94CLD6JN","Colt","Ray","eu nulla at",73, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9297414688,"Madison","EKF27UMQ8PP","Madison","Day","ornare",74, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1335477475,"Hedley","LMK68SLQ3KV","Hedley","Day","in, hendrerit consectetuer, cursus et, magna. Praesent interdum",75, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7043685891,"Lydia","GOG71GIK5LV","Lydia","Velasquez","Proin",76, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (4033702013,"Iris","RYL13XFO0XU","Iris","Wilson","est, congue a, aliquet vel, vulputate",77, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9730587122,"Hedy","BDM07LPR7AI","Hedy","Graham","vel arcu. Curabitur ut odio vel est tempor",78, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (3723614040,"Ori","YSW61SVC9UD","Ori","Knowles","Morbi non",79, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8604025824,"Elton","FFH25YWX4FV","Elton","Rollins","nec enim. Nunc",80, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (5746380819,"Joan","YKT81MJQ2FW","Joan","Wallace","natoque penatibus et magnis dis",81, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7484925001,"Nell","DHG40PXW7MV","Nell","Wade","risus. In",82, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7119486655,"Tara","JSV31UHC9BG","Tara","Mclean","mi enim, condimentum",83, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (807873555,"Casey","SGS99RUW8NG","Casey","Castro","rutrum lorem ac risus. Morbi metus.",84, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (540283738,"Knox","LHT81ICU3EN","Knox","Hickman","lorem, eget mollis lectus pede et risus.",85, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7259666988,"Mona","ZCJ72HNK2PW","Mona","Benson","nec ligula consectetuer rhoncus. Nullam velit",86, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (461038196,"Richard","SWM34SUW4NW","Richard","Howell","enim mi tempor lorem, eget mollis",87, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (966468607,"Larissa","AAU77PHT6JM","Larissa","Alston","feugiat tellus lorem eu metus.",88, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (6317531538,"Brooke","OZF31HQP9SQ","Brooke","Pittman","et",89, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (9669367805,"Kibo","FWT14IYL4OZ","Kibo","Bell","nec metus facilisis lorem tristique",90, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8216285400,"Channing","CGF83XHC9HI","Channing","Sharp","et pede. Nunc sed orci lobortis augue scelerisque",91, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (6126924847,"Fitzgerald","GSA87ABW7XY","Fitzgerald","Tyson","sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut",92, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7657199713,"Carissa","SJF87PNP5DW","Carissa","Talley","Integer vitae nibh.",93, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (8507026644,"Gemma","WTP27QSQ9MJ","Gemma","Stokes","Vivamus rhoncus. Donec est.",94, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (5462513793,"Emily","EAG21AEB6AY","Emily","Dickerson","id, libero. Donec consectetuer mauris",95, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (1732347098,"Colleen","OBK63EJF0XK","Colleen","Sweet","dictum",96, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (2549170561,"Ava","IML47IIZ6MO","Ava","Cantrell","Vestibulum accumsan neque et nunc. Quisque ornare",97, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (6697004782,"Rhonda","FSI49DUU9BD","Rhonda","Howard","sit amet orci. Ut sagittis",98, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7988350121,"Ray","DJB14RMP1DU","Ray","Mcknight","Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales",99, '0', 'Göteborg', '');
INSERT INTO `runner` (`pnr`,`username`,`userpw`,`firstname`,`lastname`,`userinfo`,`runnerid`, points, city, picture) VALUES (7208581847,"Ashely","COJ33HOV7JY","Ashely","Duncan","sem",100, '0', 'Göteborg', '');


INSERT INTO team (title, teaminfo, dateofcreation, openteam) VALUES ('IxD Grupp 5', 'Grupp 5', "10042013", 0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Natoque Penatibus Foundation","Public Relations","24012013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Erat LLP","Asset Management","26022013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Orci Corporation","Finances","26062014",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Mi Pede Consulting","Asset Management","16072014",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Dui Institute","Accounting","11052014",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Enim Nunc Industries","Finances","23052013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Volutpat PC","Advertising","20072014",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Vulputate Posuere Institute","Customer Relations","22052013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Porttitor Eros Inc.","Accounting","18122013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Pellentesque Company","Quality Assurance","04042013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Donec LLC","Advertising","30052014",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Sed LLP","Media Relations","28092014",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Mattis Incorporated","Legal Department","30112013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Proin Consulting","Human Resources","10052013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Adipiscing Enim Consulting","Payroll","28082014",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("At Risus Incorporated","Public Relations","05012013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("In Consulting","Research and Development","20102012",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Sed Foundation","Customer Relations","11092013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Vehicula Et Rutrum PC","Media Relations","20012013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Risus Donec Inc.","Tech Support","10122013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Turpis Nec Mauris Institute","Public Relations","28062014",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Dolor Sit Foundation","Asset Management","14042013",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Sollicitudin Corporation","Media Relations","05072014",0);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Vel Est Foundation","Public Relations","01012014",0);


INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Chalmers","Spring för Chalmers!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("GU","Spring för GU!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Volvo","Spring för Volvo!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Göteborg","Spring för Göteborg!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Stockholm","Spring för Stockholm!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Malmö","Spring för Malmö!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Falköping","Spring för Falköping!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Skövde","Spring för Skövde!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("IFK Göteborg","Spring för IFK!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Gais","Spring för Gais!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Hjärt-lungfonden","Spring för Hjärt-lungfonden!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Rädda Barnen","Spring för Rädda Barnen!","01012014",1);
INSERT INTO `team` (`title`,`teaminfo`,`dateofcreation`,`openteam`) VALUES ("Rädda Joppe","Rädda Joppe, död eller levande!!","01012014",1);


INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('9010242142','IxD Grupp 5');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8910152142','IxD Grupp 5');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8911232415','IxD Grupp 5');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('9003152142','IxD Grupp 5');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8912112242','IxD Grupp 5');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('9010242142','Falköping');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('9010242142','Göteborg');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8910152142','Skövde');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8910152142','Göteborg');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8911232415','Göteborg');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8911232415','Chalmers');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8911232415','Rädda Joppe');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('9003152142','Chalmers');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('9003152142','Hjärt-lungfonden');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8912112242','Göteborg');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8912112242','Rädda Barnen');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8912112242','Gais');
INSERT INTO `teamsquad`(`runnerpnr`, `teamtitle`) VALUES ('8912112242','Chalmers');

INSERT INTO `league`(`title`, `leagueinfo`) VALUES ('Chalmers-ligan','Chalmers-ligan!');
INSERT INTO `leaguemembers`(`teamtitle`, `leaguetitle`) VALUES ('IxD Grupp 5','Chalmers-ligan');

INSERT INTO `league`(`title`, `leagueinfo`) VALUES ('Stadskampen','Stadskampen!');
INSERT INTO `leaguemembers`(`teamtitle`, `leaguetitle`) VALUES ('Göteborg','Stadskampen');
INSERT INTO `leaguemembers`(`teamtitle`, `leaguetitle`) VALUES ('Falköping','Stadskampen');
INSERT INTO `leaguemembers`(`teamtitle`, `leaguetitle`) VALUES ('Skövde','Stadskampen');